#!/usr/bin/env bash
# Provision this checkout's toolchain in one command; re-run it in every new worktree, after adding
# source files and after changing a pin. Needs curl, sha256sum, tar, flock, git, cc, node and npm.
#
#   .haxe                      -> the pinned Haxe 5 compiler (tools/haxe-build.pin)
#   .haxelib/<lib>/.dev        -> the libraries all.hxml names, at the commits pinned below (read by tools/haxelib)
#   .serena/lsp.hxml           -> display config for the language server: all.hxml's HashLink/SDL build
#   .serena/project.local.yml  -> points Serena at the pinned haxe-language-server and at .haxe
#   .ast-grep/{ast-grep,haxe.so} -> the pinned ast-grep and the Haxe grammar sgconfig.yml names
#
# Everything downloaded or built is shared by every checkout of this user, one directory per pin, under
# ${XDG_CACHE_HOME:-~/.cache}/haxe-toolchain/{haxe,lib,language-server,ast-grep,tree-sitter-haxe}; nothing is ever removed from it.
# Compile with:  PATH="$PWD/tools:$PATH" HAXE_STD_PATH=.haxe/std .haxe/haxe all.hxml
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/haxe-toolchain"
die() { echo "setup: $*" >&2; exit 1; }

LOCAL="$ROOT/.serena/project.local.yml"
MARK="# GENERATED by tools/setup.sh"
if [ -f "$LOCAL" ] && grep -qv '^\s*\(#\|$\)' "$LOCAL" && ! grep -qF "$MARK" "$LOCAL"; then
  die "$LOCAL holds your own overrides; move them aside and re-run"
fi

# --- compiler: a build of the GeTechG/haxe fork, named by its build key ---------------------------------
read -r KEY SUM < "$ROOT/tools/haxe-build.pin"
[[ "$KEY" =~ ^[0-9a-f]{40}$ && "$SUM" =~ ^[0-9a-f]{64}$ ]] || die "tools/haxe-build.pin is not '<build key> <sha256>'"
HAXE_DIR="$CACHE/haxe/$KEY"
mkdir -p "$CACHE/haxe" "$CACHE/lib" "$CACHE/language-server" "$CACHE/ast-grep" "$CACHE/tree-sitter-haxe"
# One provisioner at a time: a second checkout waits here, then finds the finished installs.
exec 9> "$CACHE/.lock"
flock 9
if [ ! -x "$HAXE_DIR/haxe" ]; then
  TMP="$(mktemp -d "$HAXE_DIR.tmp.XXXXXX")"
  trap 'rm -rf "$TMP"' EXIT
  ASSET="haxe-linux64-$KEY.tar.gz"
  echo "setup: downloading $ASSET"
  curl -fsSL --retry 3 -o "$TMP/$ASSET" "https://github.com/GeTechG/haxe/releases/download/builds/$ASSET" \
    || die "no build $ASSET in release 'builds' of GeTechG/haxe"
  GOT="$(sha256sum "$TMP/$ASSET" | cut -d' ' -f1)"
  [ "$GOT" = "$SUM" ] || die "$ASSET does not match tools/haxe-build.pin: expected $SUM, got $GOT"
  mkdir "$TMP/install"
  tar -xzf "$TMP/$ASSET" -C "$TMP/install"
  [ -x "$TMP/install/haxe" ] && [ -d "$TMP/install/std" ] || die "$ASSET holds no haxe + std/"
  mv -T "$TMP/install" "$HAXE_DIR"
  rm -rf "$TMP"
fi

# --- libraries: name, GitHub repository, commit, directory inside it -------------------------------------
# The mapping is built aside and swapped in with `.haxe` only once everything is fetched and built, so a
# failed run leaves the checkout as it was.
NEW="$ROOT/.haxelib.tmp"
rm -rf "$NEW"
mkdir -p "$NEW/heaps"
echo "$ROOT" > "$NEW/heaps/.dev"
while read -r NAME REPO COMMIT SUB; do
  DIR="$CACHE/lib/${REPO#*/}/$COMMIT"
  if [ ! -d "$DIR" ]; then
    mkdir -p "$(dirname "$DIR")"
    TMP="$DIR.tmp.$$"
    trap 'rm -rf "$TMP"' EXIT
    git init -q "$TMP"
    git -C "$TMP" fetch -q --depth 1 "https://github.com/$REPO" "$COMMIT"
    git -C "$TMP" checkout -q FETCH_HEAD
    mv -T "$TMP" "$DIR"
  fi
  [ -f "$DIR/$SUB/haxelib.json" ] || die "no library at $DIR/$SUB"
  mkdir -p "$NEW/$NAME"
  (cd "$DIR/$SUB" && pwd) > "$NEW/$NAME/.dev"
done <<'EOF'
format   HaxeFoundation/format   775a06f0a7aa64cbd060b5c3ba62f65d7fed684a .
hxbit    ncannasse/hxbit         50f852cf499bdbdc5f77b0c9a8d01115a1655455 .
castle   ncannasse/castle        190a10ada1811bb62de9c700dc196437be46a45b .
hlsdl    HaxeFoundation/hashlink 3b7bd74aa316583e4b7a48859d6ec3a07a24e5f7 libs/sdl
hlopenal HaxeFoundation/hashlink 3b7bd74aa316583e4b7a48859d6ec3a07a24e5f7 libs/openal
hldx     HaxeFoundation/hashlink 3b7bd74aa316583e4b7a48859d6ec3a07a24e5f7 libs/directx
EOF

# --- language server ------------------------------------------------------------------------------------
# Built from source: the published vshaxe (2.34.2) only speaks `--wait stdio`, a mode Haxe 5 dropped;
# this commit talks to the compiler over a socket.
LS_COMMIT=e865ce6ffa9299960d558728948691b7a5e9d4a2
LS_DIR="$CACHE/language-server/$LS_COMMIT"
if [ ! -f "$LS_DIR/bin/server.js" ]; then
  TMP="$LS_DIR.tmp.$$"
  trap 'rm -rf "$TMP"' EXIT
  echo "setup: building haxe-language-server $LS_COMMIT"
  git init -q "$TMP"
  git -C "$TMP" fetch -q --depth 1 https://github.com/vshaxe/haxe-language-server "$LS_COMMIT"
  git -C "$TMP" checkout -q FETCH_HEAD
  (cd "$TMP" && npm ci --silent && npx lix run vshaxe-build -t language-server > /dev/null)
  [ -f "$TMP/bin/server.js" ] || die "the language server build produced no bin/server.js"
  mv -T "$TMP" "$LS_DIR"
fi

# --- ast-grep: structural search of the Haxe sources -----------------------------------------------------
# The binary is the npm package at an exact version (node and npm are needed for the language server
# anyway). ast-grep knows no Haxe: sgconfig.yml loads the grammar, GeTechG/tree-sitter-haxe, which
# commits its generated parser, so the system C compiler is the whole build.
AG_VERSION=0.45.3
GRAMMAR_COMMIT=31ae7eb010e18975fd73cd65e14c71ef5054f9c7
AG_DIR="$CACHE/ast-grep/$AG_VERSION"
AG_BIN="$AG_DIR/node_modules/.bin/ast-grep"
GRAMMAR_DIR="$CACHE/tree-sitter-haxe/$GRAMMAR_COMMIT"
if [ ! -x "$AG_BIN" ]; then
  TMP="$(mktemp -d "$AG_DIR.tmp.XXXXXX")"
  trap 'rm -rf "$TMP"' EXIT
  echo "setup: installing ast-grep $AG_VERSION"
  npm install --silent --no-save --no-package-lock --prefix "$TMP" "@ast-grep/cli@$AG_VERSION"
  [ "$("$TMP/node_modules/.bin/ast-grep" --version)" = "ast-grep $AG_VERSION" ] || die "npm left no ast-grep $AG_VERSION"
  mv -T "$TMP" "$AG_DIR"
fi
if [ ! -f "$GRAMMAR_DIR/haxe.so" ]; then
  TMP="$GRAMMAR_DIR.tmp.$$"
  trap 'rm -rf "$TMP"' EXIT
  echo "setup: building tree-sitter-haxe $GRAMMAR_COMMIT"
  git init -q "$TMP"
  git -C "$TMP" fetch -q --depth 1 https://github.com/GeTechG/tree-sitter-haxe "$GRAMMAR_COMMIT"
  git -C "$TMP" checkout -q FETCH_HEAD
  mkdir "$TMP/out"
  cc -shared -fPIC -O2 -I "$TMP/src" "$TMP"/src/*.c -o "$TMP/out/haxe.so"
  mv -T "$TMP/out" "$GRAMMAR_DIR"
  rm -rf "$TMP"
fi
flock -u 9

ln -sfn "$HAXE_DIR" "$ROOT/.haxe"
mkdir -p "$ROOT/.ast-grep"
ln -sfn "$AG_BIN" "$ROOT/.ast-grep/ast-grep"
ln -sfn "$GRAMMAR_DIR/haxe.so" "$ROOT/.ast-grep/haxe.so"
rm -rf "$ROOT/.haxelib"
mv -T "$NEW" "$ROOT/.haxelib"

# --- display config -------------------------------------------------------------------------------------
# The server sends these arguments to the compiler over a socket, so: no -lib (flattened to -cp/-D here)
# and no --macro. `--macro include` fails in display mode, and with no module named the compiler's cache
# build types nothing and reference lookups silently miss call sites; hence every module all.hxml
# includes is listed by name.
mkdir -p "$ROOT/.serena"
cd "$ROOT"
mapfile -t PACKAGES < <(sed -n "s/^--macro include('\([^']*\)'.*/\1/p" all.hxml)
[ "${#PACKAGES[@]}" -gt 0 ] || die "all.hxml includes no package"
IGNORED="$(grep '^--macro include' all.hxml | grep -o "\[[^]]*\]" | grep -o "'[^']*'" | tr -d "'" | sed 's/\./\\./g' | paste -sd'|')"
{
  echo "$MARK — do not edit."
  echo "-cp ."
  tools/haxelib path heaps castle hxbit hlsdl hlopenal | grep -vxF "$ROOT/" | sed 's/^\//-cp \//'
  echo "-D apicheck"
  echo "-D hl-ver=1.15.0"
  echo "-hl bin/lsp.hl"
  find "${PACKAGES[@]}" -name '*.hx' ! -name 'import.hx' ! -name '*.*.hx' | sed 's/\.hx$//; s/\//./g' \
    | grep -vE "^($IGNORED)(\.|$)" | LC_ALL=C sort
} > .serena/lsp.hxml

# Serena overwrites project.local.yml when it has to auto-generate a missing project.yml.
[ -f .serena/project.yml ] || printf 'language_servers:\n- haxe\n' > .serena/project.yml
cat > "$LOCAL" <<YAML
$MARK — do not edit.
language_servers:
- haxe
ls_specific_settings:
  haxe:
    buildFile: .serena/lsp.hxml
    ls_base_cmd: ["sh", "-c", 'PATH="\$PWD/.haxe:\$PATH" HAXE_STD_PATH="\$PWD/.haxe/std" exec node "$LS_DIR/bin/server.js"']
    ls_args: []
YAML

echo "setup: $(.haxe/haxe --version) at .haxe, $(grep -c '^[a-z0-9]' .serena/lsp.hxml) modules in .serena/lsp.hxml"
echo "setup: $(.ast-grep/ast-grep --version) at .ast-grep, Haxe grammar ${GRAMMAR_COMMIT:0:7}"
# A module that does not compile leaves reference lists incomplete again.
HAXE_STD_PATH=.haxe/std .haxe/haxe .serena/lsp.hxml --no-output \
  || die ".serena/lsp.hxml does not compile: language-server reference lists will be incomplete"
